inherit_from: .rubocop_todo.yml
require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rake

AllCops:
  TargetRubyVersion: 2.4
  DisplayCopNames: true
  DisplayStyleGuide: true
  NewCops: enable
  Include:
    - '**/Gemfile'
    - '**/Rakefile'
    - '**/*.rb'

Layout/AssignmentIndentation:
  IndentationWidth: 4

Layout/FirstArgumentIndentation:
  EnforcedStyle: consistent
  IndentationWidth: 4

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/LineLength:
  Max: 107
  AllowHeredoc: true
  AllowURI: true
  IgnoreCopDirectives: true

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
  IndentationWidth: 4

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented
  IndentationWidth: 4

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation
  IndentationWidth: 4

Metrics/BlockLength:
  Exclude:
    - '*.gemspec'

Naming/FileName:
  Exclude:
    - 'activerecord-time.gemspec'
    - 'lib/activerecord-time.rb'

Rails:
  Enabled: true

Security/Eval:
  Exclude:
    - 'gemfiles/*.gemfile'

Style/Documentation:
  Enabled: false

Style/Encoding:
  Enabled: true

Style/FormatString:
  EnforcedStyle: percent

Style/FormatStringToken:
  EnforcedStyle: unannotated

Style/NumericPredicate:
  Enabled: false

Style/RescueStandardError:
  EnforcedStyle: implicit

Style/SafeNavigation:
  ConvertCodeThatCanStartToReturnNil: true

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
